#ifndef VMDOCUMENTEDITOR_GLOBAL_H
#define VMDOCUMENTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VMDOCUMENTEDITOR_LIBRARY)
#  define VMDOCUMENTEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VMDOCUMENTEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VMDOCUMENTEDITOR_GLOBAL_H
