#ifndef VMCALCULATOR_GLOBAL_H
#define VMCALCULATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VMCALCULATOR_LIBRARY)
#  define VMCALCULATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VMCALCULATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VMCALCULATOR_GLOBAL_H
