#ifndef VMSTRINGRECORD_GLOBAL_H
#define VMSTRINGRECORD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VMSTRINGRECORD_LIBRARY)
#  define VMSTRINGRECORDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VMSTRINGRECORDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VMSTRINGRECORD_GLOBAL_H
