#ifndef VMTASKPANEL_GLOBAL_H
#define VMTASKPANEL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(VMTASKPANEL_LIBRARY)
#  define VMTASKPANELSHARED_EXPORT Q_DECL_EXPORT
#else
#  define VMTASKPANELSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // VMTASKPANEL_GLOBAL_H
